"""Initial schema

Revision ID: 8321c8f6eed7
Revises: None
Create Date: 2026-08-12 15:14:58.581670

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8321c8f6eed7'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_telegram_id'), 'admin_users', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.create_table('allowed_chats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allowed_chats_chat_id'), 'allowed_chats', ['chat_id'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_no', sa.String(length=64), nullable=False),
    sa.Column('nickname', sa.String(length=128), nullable=True),
    sa.Column('user_type', sa.String(length=32), nullable=True),
    sa.Column('month_order_count', sa.Integer(), nullable=False),
    sa.Column('month_finish_rate', sa.Float(), nullable=False),
    sa.Column('positive_rate', sa.Float(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('auto_reply_msg', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchants_nickname'), 'merchants', ['nickname'], unique=False)
    op.create_index(op.f('ix_merchants_user_no'), 'merchants', ['user_no'], unique=True)
    op.create_table('monitoring_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('asset', sa.String(length=16), nullable=False),
    sa.Column('fiat', sa.String(length=16), nullable=False),
    sa.Column('trade_type', sa.String(length=16), nullable=False),
    sa.Column('pay_types', sa.JSON(), nullable=True),
    sa.Column('trans_amount', sa.String(length=32), nullable=True),
    sa.Column('merchant_check', sa.Boolean(), nullable=False),
    sa.Column('scan_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('is_baseline_completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('advertisements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('adv_no', sa.String(length=64), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('asset', sa.String(length=16), nullable=False),
    sa.Column('fiat', sa.String(length=16), nullable=False),
    sa.Column('trade_type', sa.String(length=16), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('max_amount', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('pay_methods', sa.JSON(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('auto_reply', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advertisements_adv_no'), 'advertisements', ['adv_no'], unique=True)
    op.create_index(op.f('ix_advertisements_asset'), 'advertisements', ['asset'], unique=False)
    op.create_index(op.f('ix_advertisements_fiat'), 'advertisements', ['fiat'], unique=False)
    op.create_index(op.f('ix_advertisements_trade_type'), 'advertisements', ['trade_type'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.Column('raw_match', sa.String(length=256), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'type', 'value', name='uq_merchant_contact')
    )
    op.create_index(op.f('ix_contacts_type'), 'contacts', ['type'], unique=False)
    op.create_index(op.f('ix_contacts_value'), 'contacts', ['value'], unique=False)
    op.create_table('scan_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_ads_found', sa.Integer(), nullable=False),
    sa.Column('unique_merchants_found', sa.Integer(), nullable=False),
    sa.Column('new_merchants_count', sa.Integer(), nullable=False),
    sa.Column('new_contacts_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['monitoring_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scan_history')
    op.drop_index(op.f('ix_contacts_value'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_type'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_advertisements_trade_type'), table_name='advertisements')
    op.drop_index(op.f('ix_advertisements_fiat'), table_name='advertisements')
    op.drop_index(op.f('ix_advertisements_asset'), table_name='advertisements')
    op.drop_index(op.f('ix_advertisements_adv_no'), table_name='advertisements')
    op.drop_table('advertisements')
    op.drop_table('system_settings')
    op.drop_table('monitoring_profiles')
    op.drop_index(op.f('ix_merchants_user_no'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_nickname'), table_name='merchants')
    op.drop_table('merchants')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_allowed_chats_chat_id'), table_name='allowed_chats')
    op.drop_table('allowed_chats')
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.drop_index(op.f('ix_admin_users_telegram_id'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
